
 /* PRIMEIRA FORMA NORMAL */


/*
1 - TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA 
[AMARELO,AZUL,LARANJA,VERDE] -> CORES
[KA,FIESTA,UNO CIVIC] -> CARROS
2 - TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA QUANDO O CAMPO FOR DIVISIVEL
3 - TODA A TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COM SENDO UNICO.
ISSO E O QUE CHAMAMOS DE CHAVE PRIMARIA, OU PRIMARY KEY.
*/

  /* CARDINALIDADE */

/*  QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGOCIOS
0 - NAO OBRIGATORIO
1 - OBRIGATORIO

SEGUNDO ALGARISMO - CARDINALIDADE
1 - MAXIMO DE UM
N - MAIS DE UM
*/

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL, 
    SEXO ENUM('M','F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE

);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES','COM','CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (IDCLIENTE)
 
);
/* 
CHAVE ESTRANGEIRA É A CHAVE PRIMARIA DE UMA TABELA 
QUE VAI ATÉ A OUTRA TABELA PARA FAZER
REFERENCIA ENTRE REGISTROS */
/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAI FRACA */

/* EM RELACIONAMENTO 1 X N A CHAVE ESTRAMGEIRA FICA SEMPRE NA 
CARDINALIDADE N */

SELECT * FROM CLIENTE;

DROP TABLE CLIENTE;

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M', 'JOAO@IG.COM','767272777');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M', 'CARLOS@IG.COM','23245666');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F', 'ANA@IG.COM','4545454545');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F', NULL,'58744444');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M', 'JORGE@IG.COM','854545454');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F', 'CELIA@IG.COM','575755355');

DESC ENDERECO;
INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B.HORIZONTE','MG',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',6);

SELECT * FROM ENDERECO;

DESC TELEFONE;

INSERT INTO TELEFONE VALUES(NULL,'CEL','78458283',6);
INSERT INTO TELEFONE VALUES(NULL,'RES','77383838',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','323232323',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','33322222',3);
INSERT INTO TELEFONE VALUES(NULL,'RES','74748393',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','774383939',4);
INSERT INTO TELEFONE VALUES(NULL,'CEL','6473939393',4);
INSERT INTO TELEFONE VALUES(NULL,'COM','477338388',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','323223444',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','533333332',3);

/* SELEÇÃO, PROJEÇÃO, JUNCAO */

/*PROJECAO -> É TUDO QUE VOCE QUER VER NA TELA */

SELECT NOW() AS DATA_ATUAL;

SELECT 2+2 AS SOMAS;

SELECT 2+2 AS SOMA,NOME,NOW()
FROM CLIENTE;

/* SELECAO -> É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA
A CLAUSULA DE SELECAO É O WHERE */

SELECT NOME,SEXO,EMAIL /*PROJECAO*/
FROM CLIENTE /*ORIGEM*/
WHERE SEXO = 'F'; /* SELECAO*/

SELECT NUMERO /*PROJECAO*/
FROM TELEFONE /*ORIGEM*/
WHERE TIPO = 'CEL'; /* SELECAO*/

/* JUNCAO -> JOIN */

SELECT NOME , EMAIL, IDCLIENTE /* PROJECAO */
FROM CLIENTE;

SELECT ID_CLIENTE , BAIRRO , CIDADE
FROM ENDERECO;

/* NOME, SEXO, BAIRRO,CIDADE */

SELECT NOME,SEXO,BAIRRO,CIDADE /* PROJECAO */
FROM CLIENTE,ENDERECO /*ORIGEM*/
WHERE IDCLIENTE = ID_CLIENTE; /* SELECAO*/

/*WHERE = SELECAO */

SELECT NOME,SEXO,BAIRRO,CIDADE 
FROM CLIENTE,ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE 
AND SEXO = 'F';

/* INNER JOIN */

SELECT NOME,SEXO,BAIRRO,CIDADE  /* PROJECAO */
FROM CLIENTE /*ORIGEM*/
    INNER JOIN ENDERECO /* JUNCAO*/
    ON IDCLIENTE = ID_CLIENTE /* JUNCAO*/
WHERE SEXO = 'F'; /* SELECAO*/

/* NOME, SEXO, EMAIL,NUMERO */

SELECT NOME,SEXO,EMAIL,TIPO,NUMERO
FROM CLIENTE
    INNER JOIN TELEFONE 
    ON IDCLIENTE = ID_CLIENTE;

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO */
SELECT CLIENTE.NOME,CLIENTE.SEXO,ENDERECO.BAIRRO,ENDERECO.CIDADE,TELEFONE.TIPO,TELEFONE.NUMERO
FROM CLIENTE
    INNER JOIN ENDERECO
    ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
    INNER JOIN TELEFONE
    ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;   

+--------+------+---------+----------------+------+------------+
| NOME   | SEXO | BAIRRO  | CIDADE         | TIPO | NUMERO     |
+--------+------+---------+----------------+------+------------+
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | CEL  | 323232323  |
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | RES  | 74748393   |
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | COM  | 477338388  |
| CARLOS | M    | ESTACIO | RIO DE JANEIRO | COM  | 33322222   |
| CARLOS | M    | ESTACIO | RIO DE JANEIRO | CEL  | 533333332  |
| ANA    | F    | JARDINS | SAO PAULO      | CEL  | 774383939  |
| ANA    | F    | JARDINS | SAO PAULO      | CEL  | 6473939393 |
| JORGE  | M    | CENTRO  | VITORIA        | CEL  | 78458283   |
| JORGE  | M    | CENTRO  | VITORIA        | RES  | 77383838   |
| JORGE  | M    | CENTRO  | VITORIA        | RES  | 323223444  |
+--------+------+---------+----------------+------+------------+

/* PONTEIRAMENTO */
SELECT C.NOME,C.SEXO,E.BAIRRO,E.CIDADE,T.TIPO,T.NUMERO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;  

/*

    DML - DATA MANIPULATION LANGUAGE
    DDL - DATA DEFINITION LANGUAGE
    DCL - DATA CONTROL LANGUAGE
    TCL - TRANSACTION CONTROL LANGUAGE

*/

/* INSERT */

INSERT INTO CLIENTE VALUES(NULL,'PAULA','M',NULL,'77437493');
/* PARA DESCOBRIR ID ->  SELECT * FROM CLIENTE;*/
/* PARA DESCOBRIR SE ESTA CERTO OS INDICES DA TABELA ->  DESC ENDERECO;*/
INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIN SILVA','ALVORADA','NITEROI','RJ',14);

/* FILTROS */

SELECT * FROM CLIENTE 
WHERE SEXO = 'M';

/* UPDATE */

SELECT * FROM CLIENTE 
WHERE IDCLIENTE = 14;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 6 OR IDCLIENTE = 12 OR IDCLIENTE = 13 OR IDCLIENTE = 14 OR IDCLIENTE = 18 OR IDCLIENTE = 19 ;

/* DELETE */

INSERT INTO CLIENTE VALUES(NULL,'XXX','M',NULL,'XXXXX');

SELECT * FROM CLIENTE 
WHERE IDCLIENTE = 15;

DELETE FROM CLIENTE
WHERE IDCLIENTE = 15;


/* DDL - DATA DEFINITION LANGUAGE */

CREATE TABLE PRODUTO (
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(30) NOT NULL,
    PRECO INT,
    FRETE FLOAT(10,2) NOT NULL
);

/* ALTER TABLE */

/* ALTERANDO O NOME DE UMA COLUNA - CHANGE */

ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

DESC PRODUTO;

ALTER TABLE PRODUTO
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;

/* MODIFY - ALTERANDO O TIPO */

ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

/* ADICIONANDO COLUNAS */

ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;

/* APAGANDO UMA COLUNA */

ALTER TABLE PRODUTO
DROP COLUMN PESO;

/* ADICIONANDO UMA COLUNA NA ORDEM ESPECIFICA*/

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;

/* EXERCICIOS DML */

INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

/* CADASTRE UM ENDERECO PARA CADA CLIENTE */

INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);

/* CADASTRE TELEFONES PARA OS CLIENTES */


INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',11);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',18);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',20);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',8);

/* RELATORIO GERAL DE TODOS OS CLIENTES */

SELECT  C.NOME,C.SEXO,C.CPF,C.EMAIL,C.IDCLIENTE,
        E.RUA,E.BAIRRO,E.CIDADE,E.ESTADO,
        T.TIPO,T.NUMERO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;  

+---------+------+-------------+-------------------+--------------------+------------+----------------+--------+------+----------+-----------+
| NOME    | SEXO | CPF         | EMAIL             | RUA                | BAIRRO     | CIDADE         | ESTADO | TIPO | NUMERO   | IDCLIENTE |
+---------+------+-------------+-------------------+--------------------+------------+----------------+--------+------+----------+-----------+
| JOAO    | M    | 76567587887 | JOAOA@IG.COM      | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 87866896 |         1 |
| JOAO    | M    | 76567587887 | JOAOA@IG.COM      | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 99667587 |         1 |
| JOAO    | M    | 76567587887 | JOAOA@IG.COM      | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 66687899 |         1 |
| CARLOS  | M    | 5464553466  | CARLOSA@IG.COM    | RUA ALFANDEGA      | ESTACIO    | RIO DE JANEIRO | RJ     | COM  | 54768899 |         2 |
| CARLOS  | M    | 5464553466  | CARLOSA@IG.COM    | RUA ALFANDEGA      | ESTACIO    | RIO DE JANEIRO | RJ     | CEL  | 88687909 |         2 |
| ANA     | F    | 456545678   | ANA@IG.COM        | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     | CEL  | 78989765 |         3 |
| ANA     | F    | 456545678   | ANA@IG.COM        | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     | CEL  | 99766676 |         3 |
| JORGE   | M    | 8756547688  | JORGE@IG.COM      | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     | CEL  | 78458743 |         5 |
| JORGE   | M    | 8756547688  | JORGE@IG.COM      | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     | RES  | 56576876 |         5 |
| JORGE   | M    | 8756547688  | JORGE@IG.COM      | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     | RES  | 89986668 |         5 |
| FLAVIO  | M    | 4657765     | FLAVIO@IG.COM     | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 44522578 |         8 |
| ANDRE   | M    | 7687567     | ANDRE@GLOBO.COM   | RUA GUEDES         | CASCADURA  | B. HORIZONTE   | MG     | RES  | 68976565 |         9 |
| ANDRE   | M    | 7687567     | ANDRE@GLOBO.COM   | RUA GUEDES         | CASCADURA  | B. HORIZONTE   | MG     | CEL  | 99656675 |         9 |
| KARLA   | M    | 545676778   | KARLA@GMAIL.COM   | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 33567765 |        11 |
| KARLA   | M    | 545676778   | KARLA@GMAIL.COM   | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 88668786 |        11 |
| KARLA   | M    | 545676778   | KARLA@GMAIL.COM   | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 55689654 |        11 |
| DANIELE | M    | 43536789    | DANIELE@GMAIL.COM | RUA NELSON MANDELA | COPACABANA | RIO DE JANEIRO | RJ     | COM  | 88687979 |        12 |
| LORENA  | M    | 774557887   | NULL              | RUA ARAUJO LIMA    | CENTRO     | VITORIA        | ES     | COM  | 88965676 |        13 |
| ANTONIO | F    | 12436767    | ANTONIO@IG.COM    | AV CAPITAO ANTUNES | CENTRO     | CURITIBA       | PR     | CEL  | 89966809 |        15 |
| ANTONIO | M    | 3423565     | ANTONIO@UOL.COM   | AV CARLOS BARROSO  | JARDINS    | SAO PAULO      | SP     | COM  | 88679978 |        16 |
| ELAINE  | M    | 32567763    | ELAINE@GLOBO.COM  | ALAMEDA SAMPAIO    | BOM RETIRO | CURITIBA       | PR     | CEL  | 99655768 |        17 |
| CARMEM  | M    | 787832213   | CARMEM@IG.COM     | RUA DA LAPA        | LAPA       | SAO PAULO      | SP     | RES  | 89955665 |        18 |
| ADRIANA | F    | 88556942    | ADRIANA@GMAIL.COM | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77455786 |        19 |
| ADRIANA | F    | 88556942    | ADRIANA@GMAIL.COM | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 89766554 |        19 |
| JOICE   | F    | 55412256    | JOICE@GMAIL.COM   | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77755785 |        20 |
+---------+------+-------------+-------------------+--------------------+------------+----------------+--------+------+----------+-----------+




/* MUNDADO SEXO INCORRETO*/

SELECT * FROM CLIENTE 
WHERE IDCLIENTE = 11;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE =6;

SELECT * FROM CLIENTE 
WHERE IDCLIENTE = 12;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 12;

SELECT * FROM CLIENTE 
WHERE IDCLIENTE = 13;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 13;

UPDATE CLIENTE
SET SEXO = 'M'
WHERE IDCLIENTE = 15;

SELECT * FROM CLIENTE 
WHERE IDCLIENTE = 17;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 17;

SELECT * FROM CLIENTE 
WHERE IDCLIENTE = 18;

UPDATE CLIENTE
SET SEXO = 'M'
WHERE IDCLIENTE = 16;

/* RELATORIO DE HOMENS*/
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

+-----------+---------+------+-------------------+-------------+--------------------+------------+----------------+--------+------+----------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF         | RUA                | BAIRRO     | CIDADE         | ESTADO | TIPO | NUMERO   |
+-----------+---------+------+-------------------+-------------+--------------------+------------+----------------+--------+------+----------+
|         1 | JOAO    | M    | JOAOA@IG.COM      | 76567587887 | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 87866896 |
|         1 | JOAO    | M    | JOAOA@IG.COM      | 76567587887 | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 99667587 |
|         1 | JOAO    | M    | JOAOA@IG.COM      | 76567587887 | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 66687899 |
|         2 | CARLOS  | M    | CARLOSA@IG.COM    | 5464553466  | RUA ALFANDEGA      | ESTACIO    | RIO DE JANEIRO | RJ     | COM  | 54768899 |
|         2 | CARLOS  | M    | CARLOSA@IG.COM    | 5464553466  | RUA ALFANDEGA      | ESTACIO    | RIO DE JANEIRO | RJ     | CEL  | 88687909 |
|         3 | ANA     | F    | ANA@IG.COM        | 456545678   | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     | CEL  | 78989765 |
|         3 | ANA     | F    | ANA@IG.COM        | 456545678   | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     | CEL  | 99766676 |
|         5 | JORGE   | M    | JORGE@IG.COM      | 8756547688  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     | CEL  | 78458743 |
|         5 | JORGE   | M    | JORGE@IG.COM      | 8756547688  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     | RES  | 56576876 |
|         5 | JORGE   | M    | JORGE@IG.COM      | 8756547688  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     | RES  | 89986668 |
|         9 | FLAVIO  | M    | FLAVIO@IG.COM     | 4657765     | RUA GUEDES         | CASCADURA  | B. HORIZONTE   | MG     | RES  | 68976565 |
|         9 | FLAVIO  | M    | FLAVIO@IG.COM     | 4657765     | RUA GUEDES         | CASCADURA  | B. HORIZONTE   | MG     | CEL  | 99656675 |
|        11 | GIOVANA | F    | NULL              | 0876655     | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 33567765 |
|        11 | GIOVANA | F    | NULL              | 0876655     | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 88668786 |
|        11 | GIOVANA | F    | NULL              | 0876655     | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 55689654 |
|        12 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778   | RUA NELSON MANDELA | COPACABANA | RIO DE JANEIRO | RJ     | COM  | 88687979 |
|        13 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789    | RUA ARAUJO LIMA    | CENTRO     | VITORIA        | ES     | COM  | 88965676 |
|        15 | EDUARDO | M    | NULL              | 54376457    | AV CAPITAO ANTUNES | CENTRO     | CURITIBA       | PR     | CEL  | 89966809 |
|        16 | ANTONIO | M    | ANTONIO@IG.COM    | 12436767    | AV CARLOS BARROSO  | JARDINS    | SAO PAULO      | SP     | COM  | 88679978 |
|        17 | ANTONIO | M    | ANTONIO@UOL.COM   | 3423565     | ALAMEDA SAMPAIO    | BOM RETIRO | CURITIBA       | PR     | CEL  | 99655768 |
|        18 | ELAINE  | F    | ELAINE@GLOBO.COM  | 32567763    | RUA DA LAPA        | LAPA       | SAO PAULO      | SP     | RES  | 89955665 |
|        19 | CARMEM  | F    | CARMEM@IG.COM     | 787832213   | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77455786 |
|        19 | CARMEM  | F    | CARMEM@IG.COM     | 787832213   | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 89766554 |
|        20 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942    | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77755785 |
|        20 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942    | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 44522578 |
|        21 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256    | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 44522578 |
+-----------+---------+------+-------------------+-------------+--------------------+------------+----------------+--------+------+----------+

/* RELATORIO DE MULHERES*/
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO ='F'; 

+-----------+---------+------+-------------------+-----------+--------------------+------------+----------------+--------+------+----------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF       | RUA                | BAIRRO     | CIDADE         | ESTADO | TIPO | NUMERO   |
+-----------+---------+------+-------------------+-----------+--------------------+------------+----------------+--------+------+----------+
|         3 | ANA     | F    | ANA@IG.COM        | 456545678 | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     | CEL  | 78989765 |
|         3 | ANA     | F    | ANA@IG.COM        | 456545678 | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     | CEL  | 99766676 |
|        11 | GIOVANA | F    | NULL              | 0876655   | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 33567765 |
|        11 | GIOVANA | F    | NULL              | 0876655   | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 88668786 |
|        11 | GIOVANA | F    | NULL              | 0876655   | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 55689654 |
|        12 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778 | RUA NELSON MANDELA | COPACABANA | RIO DE JANEIRO | RJ     | COM  | 88687979 |
|        13 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789  | RUA ARAUJO LIMA    | CENTRO     | VITORIA        | ES     | COM  | 88965676 |
|        18 | ELAINE  | F    | ELAINE@GLOBO.COM  | 32567763  | RUA DA LAPA        | LAPA       | SAO PAULO      | SP     | RES  | 89955665 |
|        19 | CARMEM  | F    | CARMEM@IG.COM     | 787832213 | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77455786 |
|        19 | CARMEM  | F    | CARMEM@IG.COM     | 787832213 | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 89766554 |
|        20 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942  | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77755785 |
|        20 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942  | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 44522578 |
|        21 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256  | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 44522578 |
+-----------+---------+------+-------------------+-----------+--------------------+------------+----------------+--------+------+----------+

/* CONTAGEM DE HOMENS E MULHERES*/

SELECT * FROM CLIENTE;

SELECT SEXO, COUNT(*) 
FROM CLIENTE
GROUP BY SEXO;

+------+----------+
| SEXO | COUNT(*) |
+------+----------+
| M    |        8 |
| F    |       12 |
+------+----------+

/* IDs e e email de MULHERES que morem no centro do rio de janeiro e não tem celular*/

SELECT C.EMAIL,E.BAIRRO,E.CIDADE,T.TIPO,C.IDCLIENTE
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO ='F' AND E.BAIRRO = 'CENTRO'AND E.CIDADE ='RIO DE JANEIRO' AND T.TIPO != 'CEL' ; 
/* AND (TIPO = 'RES' OR TIPO = 'COM'); */

+-------------------+--------+----------------+------+-----------+
| EMAIL             | BAIRRO | CIDADE         | TIPO | IDCLIENTE |
+-------------------+--------+----------------+------+-----------+
| NULL              | CENTRO | RIO DE JANEIRO | COM  |        11 |
| CARMEM@IG.COM     | CENTRO | RIO DE JANEIRO | RES  |        19 |
| CARMEM@IG.COM     | CENTRO | RIO DE JANEIRO | RES  |        19 |
| ADRIANA@GMAIL.COM | CENTRO | RIO DE JANEIRO | RES  |        20 |
| ADRIANA@GMAIL.COM | CENTRO | RIO DE JANEIRO | COM  |        20 |
+-------------------+--------+----------------+------+-----------+

/* PARA UMA CAMAPANHA DE MARKETING, O SETOR SOLICITOU UM RELATORIO COM O NOME,EMAIL, 
E TELEFONE CELULAR DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANIERO
VOCE TERA QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA UM PROGRAMADOR */

SELECT C.NOME,C.EMAIL,T.NUMERO AS CELULAR, E.ESTADO, C.IDCLIENTE
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE

WHERE E.ESTADO ='RJ' AND T.TIPO = 'CEL' ; 

+---------+-----------------+----------+--------+-----------+
| NOME    | EMAIL           | CELULAR  | ESTADO | IDCLIENTE |
+---------+-----------------+----------+--------+-----------+
| JOAO    | JOAOA@IG.COM    | 87866896 | RJ     |         1 |
| CARLOS  | CARLOSA@IG.COM  | 88687909 | RJ     |         2 |
| GIOVANA | NULL            | 33567765 | RJ     |        11 |
| GIOVANA | NULL            | 88668786 | RJ     |        11 |
| JOICE   | JOICE@GMAIL.COM | 44522578 | RJ     |        21 |
+---------+-----------------+----------+--------+-----------+

/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM RELATÓRIO COM O NOME,EMAIL E TELEFONE CELULAR
 DAS MULHERES QUE MORAM NO ESTADO DE SAO PAULO. */

SELECT C.NOME,C.SEXO,C.EMAIL,T.NUMERO AS CELULAR, E.ESTADO, C.IDCLIENTE
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE

WHERE SEXO = 'F' AND E.ESTADO ='SP' AND T.TIPO = 'CEL' ; 

+------+------+------------+----------+--------+-----------+
| NOME | SEXO | EMAIL      | CELULAR  | ESTADO | IDCLIENTE |
+------+------+------------+----------+--------+-----------+
| ANA  | F    | ANA@IG.COM | 78989765 | SP     |         3 |
| ANA  | F    | ANA@IG.COM | 99766676 | SP     |         3 |
+------+------+------------+----------+--------+-----------+


/* NOME, EMAIL, NUMERO, ESTADO */

SELECT C.NOME, C.EMAIL,E.ESTADO,T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

+---------+-------------------+--------+----------+
| NOME    | EMAIL             | ESTADO | NUMERO   |
+---------+-------------------+--------+----------+
| JORGE   | JORGE@IG.COM      | ES     | 78458743 |
| JORGE   | JORGE@IG.COM      | ES     | 56576876 |
| JOAO    | JOAOA@IG.COM      | RJ     | 87866896 |
| CARLOS  | CARLOSA@IG.COM    | RJ     | 54768899 |
| JOAO    | JOAOA@IG.COM      | RJ     | 99667587 |
| ANA     | ANA@IG.COM        | SP     | 78989765 |
| ANA     | ANA@IG.COM        | SP     | 99766676 |
| JOAO    | JOAOA@IG.COM      | RJ     | 66687899 |
| JORGE   | JORGE@IG.COM      | ES     | 89986668 |
| CARLOS  | CARLOSA@IG.COM    | RJ     | 88687909 |
| FLAVIO  | FLAVIO@IG.COM     | MG     | 68976565 |
| FLAVIO  | FLAVIO@IG.COM     | MG     | 99656675 |
| GIOVANA | NULL              | RJ     | 33567765 |
| GIOVANA | NULL              | RJ     | 88668786 |
| GIOVANA | NULL              | RJ     | 55689654 |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 88687979 |
| DANIELE | DANIELE@GMAIL.COM | ES     | 88965676 |
| EDUARDO | NULL              | PR     | 89966809 |
| ANTONIO | ANTONIO@IG.COM    | SP     | 88679978 |
| ANTONIO | ANTONIO@UOL.COM   | PR     | 99655768 |
| ELAINE  | ELAINE@GLOBO.COM  | SP     | 89955665 |
| CARMEM  | CARMEM@IG.COM     | RJ     | 77455786 |
| CARMEM  | CARMEM@IG.COM     | RJ     | 89766554 |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 77755785 |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 44522578 |
| JOICE   | JOICE@GMAIL.COM   | RJ     | 44522578 |
+---------+-------------------+--------+----------+

/* FUNÇÃO IFNULL */


SELECT  C.NOME, 
        IFNULL(C.EMAIL,'NAO TEM EMAIL'),
        E.ESTADO,
        T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

+---------+---------------------------------+--------+----------+
| NOME    | IFNULL(C.EMAIL,'NAO TEM EMAIL') | ESTADO | NUMERO   |
+---------+---------------------------------+--------+----------+
| JORGE   | JORGE@IG.COM                    | ES     | 78458743 |
| JORGE   | JORGE@IG.COM                    | ES     | 56576876 |
| JOAO    | JOAOA@IG.COM                    | RJ     | 87866896 |
| CARLOS  | CARLOSA@IG.COM                  | RJ     | 54768899 |
| JOAO    | JOAOA@IG.COM                    | RJ     | 99667587 |
| ANA     | ANA@IG.COM                      | SP     | 78989765 |
| ANA     | ANA@IG.COM                      | SP     | 99766676 |
| JOAO    | JOAOA@IG.COM                    | RJ     | 66687899 |
| JORGE   | JORGE@IG.COM                    | ES     | 89986668 |
| CARLOS  | CARLOSA@IG.COM                  | RJ     | 88687909 |
| FLAVIO  | FLAVIO@IG.COM                   | MG     | 68976565 |
| FLAVIO  | FLAVIO@IG.COM                   | MG     | 99656675 |
| GIOVANA | NAO TEM EMAIL                   | RJ     | 33567765 |
| GIOVANA | NAO TEM EMAIL                   | RJ     | 88668786 |
| GIOVANA | NAO TEM EMAIL                   | RJ     | 55689654 |
| KARLA   | KARLA@GMAIL.COM                 | RJ     | 88687979 |
| DANIELE | DANIELE@GMAIL.COM               | ES     | 88965676 |
| EDUARDO | NAO TEM EMAIL                   | PR     | 89966809 |
| ANTONIO | ANTONIO@IG.COM                  | SP     | 88679978 |
| ANTONIO | ANTONIO@UOL.COM                 | PR     | 99655768 |
| ELAINE  | ELAINE@GLOBO.COM                | SP     | 89955665 |
| CARMEM  | CARMEM@IG.COM                   | RJ     | 77455786 |
| CARMEM  | CARMEM@IG.COM                   | RJ     | 89766554 |
| ADRIANA | ADRIANA@GMAIL.COM               | RJ     | 77755785 |
| ADRIANA | ADRIANA@GMAIL.COM               | RJ     | 44522578 |
| JOICE   | JOICE@GMAIL.COM                 | RJ     | 44522578 |
+---------+---------------------------------+--------+----------+

SELECT  C.NOME, 
        IFNULL(C.EMAIL,'NAO TEM EMAIL') AS EMAIL,
        E.ESTADO,
        T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

+---------+-------------------+--------+----------+
| NOME    | EMAIL             | ESTADO | NUMERO   |
+---------+-------------------+--------+----------+
| JORGE   | JORGE@IG.COM      | ES     | 78458743 |
| JORGE   | JORGE@IG.COM      | ES     | 56576876 |
| JOAO    | JOAOA@IG.COM      | RJ     | 87866896 |
| CARLOS  | CARLOSA@IG.COM    | RJ     | 54768899 |
| JOAO    | JOAOA@IG.COM      | RJ     | 99667587 |
| ANA     | ANA@IG.COM        | SP     | 78989765 |
| ANA     | ANA@IG.COM        | SP     | 99766676 |
| JOAO    | JOAOA@IG.COM      | RJ     | 66687899 |
| JORGE   | JORGE@IG.COM      | ES     | 89986668 |
| CARLOS  | CARLOSA@IG.COM    | RJ     | 88687909 |
| FLAVIO  | FLAVIO@IG.COM     | MG     | 68976565 |
| FLAVIO  | FLAVIO@IG.COM     | MG     | 99656675 |
| GIOVANA | NAO TEM EMAIL     | RJ     | 33567765 |
| GIOVANA | NAO TEM EMAIL     | RJ     | 88668786 |
| GIOVANA | NAO TEM EMAIL     | RJ     | 55689654 |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 88687979 |
| DANIELE | DANIELE@GMAIL.COM | ES     | 88965676 |
| EDUARDO | NAO TEM EMAIL     | PR     | 89966809 |
| ANTONIO | ANTONIO@IG.COM    | SP     | 88679978 |
| ANTONIO | ANTONIO@UOL.COM   | PR     | 99655768 |
| ELAINE  | ELAINE@GLOBO.COM  | SP     | 89955665 |
| CARMEM  | CARMEM@IG.COM     | RJ     | 77455786 |
| CARMEM  | CARMEM@IG.COM     | RJ     | 89766554 |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 77755785 |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 44522578 |
| JOICE   | JOICE@GMAIL.COM   | RJ     | 44522578 |
+---------+-------------------+--------+----------+

/* VIEW */
/* A VIEW APARECE COMO UMA TABELA VIRTUAL */
CREATE VIEW RELATORIO AS
SELECT  C.NOME, 
        IFNULL(C.EMAIL,'NAO TEM EMAIL') AS EMAIL,
        E.ESTADO,
        T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

SELECT * FROM RELATORIO;
+---------+-------------------+--------+----------+
| NOME    | EMAIL             | ESTADO | NUMERO   |
+---------+-------------------+--------+----------+
| JORGE   | JORGE@IG.COM      | ES     | 78458743 |
| JORGE   | JORGE@IG.COM      | ES     | 56576876 |
| JOAO    | JOAOA@IG.COM      | RJ     | 87866896 |
| CARLOS  | CARLOSA@IG.COM    | RJ     | 54768899 |
| JOAO    | JOAOA@IG.COM      | RJ     | 99667587 |
| ANA     | ANA@IG.COM        | SP     | 78989765 |
| ANA     | ANA@IG.COM        | SP     | 99766676 |
| JOAO    | JOAOA@IG.COM      | RJ     | 66687899 |
| JORGE   | JORGE@IG.COM      | ES     | 89986668 |
| CARLOS  | CARLOSA@IG.COM    | RJ     | 88687909 |
| FLAVIO  | FLAVIO@IG.COM     | MG     | 68976565 |
| FLAVIO  | FLAVIO@IG.COM     | MG     | 99656675 |
| GIOVANA | NAO TEM EMAIL     | RJ     | 33567765 |
| GIOVANA | NAO TEM EMAIL     | RJ     | 88668786 |
| GIOVANA | NAO TEM EMAIL     | RJ     | 55689654 |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 88687979 |
| DANIELE | DANIELE@GMAIL.COM | ES     | 88965676 |
| EDUARDO | NAO TEM EMAIL     | PR     | 89966809 |
| ANTONIO | ANTONIO@IG.COM    | SP     | 88679978 |
| ANTONIO | ANTONIO@UOL.COM   | PR     | 99655768 |
| ELAINE  | ELAINE@GLOBO.COM  | SP     | 89955665 |
| CARMEM  | CARMEM@IG.COM     | RJ     | 77455786 |
| CARMEM  | CARMEM@IG.COM     | RJ     | 89766554 |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 77755785 |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 44522578 |
| JOICE   | JOICE@GMAIL.COM   | RJ     | 44522578 |
+---------+-------------------+--------+----------+

/* APAGANDO UMA VIEW */

DROP VIEW RELATORIO;


/* INSERINDO UM PREFIXO */

CREATE VIEW V_RELATORIO AS
SELECT  C.NOME, 
        IFNULL(C.EMAIL,'NAO TEM EMAIL') AS EMAIL,
        E.ESTADO,
        T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

SELECT NOME,NUMERO, ESTADO
FROM V_RELATORIO;

/* UPDATE,INSERT, DELETE - DML */

INSERT INTO V_RELATORIO VALUES(
'ANDREIA','F','ANDREIA@UOL.COM.BR','CEL','873547864','CENTRO','VITORIA','ES'
);

ERROR 1394 (HY000): Can not insert into join view 'comercio.v_relatorio' without fields list
ERROR 1395 (HY000): Can not delete from join view 'comercio.v_relatorio'

DELETE FROM V_RELATORIO WHERE NOME = 'JORGE';

/* É PERMITIDO FAZER UPDATES EM VIEWS COM JOIN */

UPDATE V_RELATORIO SET NOME = 'JOSE' WHERE NOME = 'JORGE';


CREATE TABLE JOGADORES(
	IDJOGADOR INT,
	NOME VARCHAR(30),
	ESTADO CHAR(2)
);

INSERT INTO JOGADORES VALUES(1,'GUERRERO','RS');
INSERT INTO JOGADORES VALUES(2,'GABIGOL','RJ');
INSERT INTO JOGADORES VALUES(3,'GANSO','RJ');
INSERT INTO JOGADORES VALUES(4,'NENÊ', 'RJ');
INSERT INTO JOGADORES VALUES(5,'LOVE','SP');


CREATE VIEW V_JOGADORES AS
SELECT NOME, ESTADO
FROM JOGADORES;

DELETE FROM V_JOGADORES
WHERE NOME = 'GUERRERO';

INSERT INTO V_JOGADORES VALUES('GUERRERO','RS');

SELECT * FROM JOGADORES;

+-----------+----------+--------+
| IDJOGADOR | NOME     | ESTADO |
+-----------+----------+--------+
|         2 | GABIGOL  | RJ     |
|         3 | GANSO    | RJ     |
|         4 | NENÊ     | RJ     |
|         5 | LOVE     | SP     |
|      NULL | GUERRERO | RS     |
+-----------+----------+--------+

SELECT * FROM V_RELATORIO
WHERE ESTADO = 'RJ';

/* ORDER BY */


CREATE TABLE ALUNOS(
    NUMERO INT,
    NOME VARCHAR(30)
);

INSERT INTO ALUNOS VALUES(1,'JOAO');
INSERT INTO ALUNOS VALUES(1,'MARIA');
INSERT INTO ALUNOS VALUES(2,'ZOE');
INSERT INTO ALUNOS VALUES(2,'ANDRE');
INSERT INTO ALUNOS VALUES(3,'CLARA');
INSERT INTO ALUNOS VALUES(1,'CLARA');
INSERT INTO ALUNOS VALUES(4,'MAFRA');
INSERT INTO ALUNOS VALUES(5,'JANAINA');
INSERT INTO ALUNOS VALUES(1,'JANAINA');
INSERT INTO ALUNOS VALUES(3,'MARCELO');
INSERT INTO ALUNOS VALUES(4,'GIOVANI');
INSERT INTO ALUNOS VALUES(5,'ANTONIO');
INSERT INTO ALUNOS VALUES(6,'ANA');
INSERT INTO ALUNOS VALUES(6,'VIVIANE'); 

SELECT * FROM ALUNOS
ORDER BY NUMERO;

SELECT * FROM ALUNOS
ORDER BY 1;

SELECT * FROM ALUNOS
ORDER BY 2;

/* ORDENANDO POR MAIS DE UMA COLUNA */

SELECT * FROM ALUNOS
ORDER BY 1;

SELECT * FROM ALUNOS
ORDER BY NUMERO,NOME;

SELECT * FROM ALUNOS
ORDER BY 1,2;

/* MESCLANDO ORDER BY COM PROJECAO */

SELECT * FROM ALUNOS
ORDER BY 1,2; /*ERRO */

SELECT NOME FROM ALUNOS
ORDER BY NUMERO,NOME;

/* ORDER BY DESC / ASC  */

SELECT * FROM ALUNOS
ORDER BY 1 ASC;

SELECT * FROM ALUNOS
ORDER BY 1 DESC;

SELECT * FROM ALUNOS
ORDER BY 1 DESC, 2 DESC;

/* ORDENANDO COM JOIN */

SELECT  C.NOME, 
        IFNULL(C.EMAIL,'NAO TEM EMAIL') AS EMAIL,
        E.ESTADO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
ORDER BY 1;

SELECT * FROM V_RELATORIO
ORDER BY 1;

/* DELIMITADOR */
STATUS

DELIMITER $

SELECT * FROM V_RELATORIO$

DELIMITER ;

/* STORED PROCEDURES */

DELIMITER $

CREATE PROCEDURA NOME()
BEGIN 
    QUALQUER PROGRAMACAO;

END
$

DELIMITER $

CREATE PROCEDURE NOMES_EMPRESA()
BEGIN

    SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;
END
$

/*CHAMANDO UMA PROCEDURE */
CALL NOMES_EMPRESA()$

DELIMITER ;
CALL NOMES_EMPRESA();

DELIMITER $
CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN
    SELECT NUMERO1 + NUMERO2 AS CONTA;
END
$

CALL CONTA(100,50)$

DELIMITER ;

CREATE DATABASE PROJETO2;
USE PROJETO2;
CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    HORAS INT(3) NOT NULL,
    VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL,'JAVA',30,500.00);
INSERT INTO CURSOS VALUES(NULL,'FUNDAMENTOS DE BANCOS DE DADOS',40,700.00);
DELIMITER #
STATUS

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30),
                           P_HORAS INT(3),
                           P_VALOR FLOAT(10,2))
BEGIN
    INSERT INTO CURSOS VALUES(NULL,P_NOME,P_HORAS,P_VALOR);
END
#
DELIMITER ;
STATUS
CALL CAD_CURSO('BI SQL SERVER',35,3000.00);
CALL CAD_CURSO('POWER BI',20,1000.00);
CALL CAD_CURSO('TABLEAU',20,1200.00);

/* CRIE UMA PROCEDURA PARA CONSULTAR CURSOS */

DELIMITER #
STATUS

CREATE PROCEDURE FIND_CURSO(P_IDCURSO INT(3))
BEGIN
    SELECT NOME,HORAS,VALOR FROM CURSOS
    WHERE IDCURSO = P_IDCURSO;
END
#
DELIMITER ;
STATUS
CALL FIND_CURSO(1);

CREATE TABLE VENDEDORES(
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    SEXO CHAR(1),
    JANEIRO FLOAT(10,2),
    FEVEREIRO FLOAT(10,2),
    MARCO FLOAT(10,2),
);

/* MAX - TRAZ O VALOR MAXIMO DE UMA COLUNA */

SELECT MAX(FEVEREIRO) AS MAIOR_FEV
FROM VENDEDORES;

/* MIN - TRAZ O VALOR MIN DE UMA COLUNA */

SELECT MIN(FEVEREIRO) AS MENOR_FEV
FROM VENDEDORES;

/* AVG - TRAZ O VALOR MEDIO DE UMA COLUNA */

SELECT AVG(FEVEREIRO) AS MEDIA_FEV
FROM VENDEDORES;


/* VARIAS FUNCOES */

SELECT MAX(JANEIRO) AS MAIOR_JAN,
       MIN(JANEIRO) AS MIN_JAN,
       AVG(JANEIRO) AS MEDIA_JAN
       FROM VENDEDORES;
/* TRUNCATE */

SELECT MAX(JANEIRO) AS MAIOR_JAN,
       MIN(JANEIRO) AS MIN_JAN,
       TRUNCATE(AVG(JANEIRO),2) AS MEDIA_JAN
       FROM VENDEDORES;       

/* TRUNCATE */

SELECT  SUM(JANEIRO) AS TOTAL_JAN,
        SUM(FEVEREIRO) AS TOTAL_FEV,
        SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDORES;

+-----------+-----------+-------------+
| TOTAL_JAN | TOTAL_FEV | TOTAL_MARCO |
+-----------+-----------+-------------+
| 995439.21 | 795141.96 |   685831.17 |
+-----------+-----------+-------------+

/* VENDAS POR SEXO */

SELECT  SEXO,SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDORES
GROUP BY SEXO;
+------+-------------+
| SEXO | TOTAL_MARCO |
+------+-------------+
| F    |    87855.60 |
| M    |   597975.57 |
+------+-------------+

/* VENDEDOR QUE VENDEU MENOS EM MARCO EO SEU NOME */

SELECT  NOME,MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

| NOME  | MARCO   |
+-------+---------+
| MARIA | 4467.90 |
+-------+---------+

SELECT  NOME,MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

| NOME     | MARCO     |
+----------+-----------+
| ANDERSON | 578665.88 |
+----------+-----------+
SELECT  NOME,FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES)
+-------+-----------+
| NOME  | FEVEREIRO |
+-------+-----------+
| CLARA | 446886.88 |
+-------+-----------+
SELECT AVG(FEVEREIRO) FROM VENDEDORES;
+----------------+
| AVG(FEVEREIRO) |
+----------------+
|   99392.744873 |
+----------------+

SELECT  NOME,MARCO FROM VENDEDORES
WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDORES); /* SE TIVESSE AND A SUBQUERY DEVE TER DUAS COLUNAS P/ COMPARAÇÃO*/

| NOME     | MARCO     |
+----------+-----------+
| ANDERSON | 578665.88 |
+----------+-----------+

/* OPERACOES EM LINHA */

SELECT * FROM VENDEDORES;

SELECT  NOME,
        JANEIRO,
        FEVEREIRO,
        MARCO,
        (JANEIRO+FEVEREIRO+MARCO) AS 'TOTAL',
        TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS 'MEDIA'
FROM VENDEDORES;

+----------+-----------+-----------+-----------+------------+-----------+
| NOME     | JANEIRO   | FEVEREIRO | MARCO     | TOTAL      | MEDIA     |
+----------+-----------+-----------+-----------+------------+-----------+
| CARLOS   |  76234.78 |  88346.87 |   5756.90 |  170338.55 |  56779.51 |
| MARIA    |   5865.78 |   6768.87 |   4467.90 |   17102.55 |   5700.84 |
| ANTONIO  |  78769.78 |   6685.87 |   6664.90 |   92120.55 |  30706.85 |
| CLARA    |   5779.78 | 446886.88 |   8965.90 |  461632.56 | 153877.51 |
| ANDERSON | 676545.75 |  77544.87 | 578665.88 | 1332756.49 | 444252.16 |
| IVONE    |  57789.78 |  44774.87 |  68665.90 |  171230.55 |  57076.85 |
| JOAO     |   4785.78 |  66478.87 |   6887.90 |   78152.55 |  26050.84 |
| CELIA    |  89667.78 |  57654.87 |   5755.90 |  153078.55 |  51026.18 |
+----------+-----------+-----------+-----------+------------+-----------+

SELECT * FROM VENDEDORES;

SELECT  NOME,
        JANEIRO,
        FEVEREIRO,
        MARCO,
        (JANEIRO+FEVEREIRO+MARCO) AS 'TOTAL',
        TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS 'MEDIA'
FROM VENDEDORES;

/* APLCAINDO UM % */

SELECT  NOME,
        JANEIRO,
        FEVEREIRO,
        MARCO,
        (JANEIRO+FEVEREIRO+MARCO) AS 'TOTAL',
        (JANEIRO+FEVEREIRO+MARCO) *.25 AS 'DESCONTO',
        TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS 'MEDIA'
FROM VENDEDORES;
+----------+-----------+-----------+-----------+------------+-----------+-----------+
| NOME     | JANEIRO   | FEVEREIRO | MARCO     | TOTAL      | DESCONTO  | MEDIA     |
+----------+-----------+-----------+-----------+------------+-----------+-----------+
| CARLOS   |  76234.78 |  88346.87 |   5756.90 |  170338.55 |  42584.64 |  56779.51 |
| MARIA    |   5865.78 |   6768.87 |   4467.90 |   17102.55 |   4275.64 |   5700.84 |
| ANTONIO  |  78769.78 |   6685.87 |   6664.90 |   92120.55 |  23030.14 |  30706.85 |
| CLARA    |   5779.78 | 446886.88 |   8965.90 |  461632.56 | 115408.14 | 153877.51 |
| ANDERSON | 676545.75 |  77544.87 | 578665.88 | 1332756.49 | 333189.12 | 444252.16 |
| IVONE    |  57789.78 |  44774.87 |  68665.90 |  171230.55 |  42807.64 |  57076.85 |
| JOAO     |   4785.78 |  66478.87 |   6887.90 |   78152.55 |  19538.14 |  26050.84 |
| CELIA    |  89667.78 |  57654.87 |   5755.90 |  153078.55 |  38269.64 |  51026.18 |
+----------+-----------+-----------+-----------+------------+-----------+-----------+

/* ALTERANDO TABELAS */

CREATE TABLE TABELA(
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

/* ADICIONANDO PRIMRARY KEY */
ALTER TABLE TABELA
ADD PRIMARY KEY (COLUNA1);

DESC TABELA;
+---------+-------------+------+-----+---------+-------+
| Field   | Type        | Null | Key | Default | Extra |
+---------+-------------+------+-----+---------+-------+
| COLUNA1 | varchar(30) | NO   | PRI | NULL    |       |
| COLUNA2 | varchar(30) | YES  |     | NULL    |       |
| COLUNA3 | varchar(30) | YES  |     | NULL    |       |
+---------+-------------+------+-----+---------+-------+

/* ADICIONANDO UMA COLUNA SEM POSIÇÃO*/
ALTER TABLE TABELA
ADD COLUNA VARCHAR (30);
+---------+-------------+------+-----+---------+-------+
| Field   | Type        | Null | Key | Default | Extra |
+---------+-------------+------+-----+---------+-------+
| COLUNA1 | varchar(30) | NO   | PRI | NULL    |       |
| COLUNA2 | varchar(30) | YES  |     | NULL    |       |
| COLUNA3 | varchar(30) | YES  |     | NULL    |       |
| COLUNA  | varchar(30) | YES  |     | NULL    |       |
+---------+-------------+------+-----+---------+-------+
ALTER TABLE TABELA
ADD COLUNA100 INT (11);
+-----------+-------------+------+-----+---------+-------+
| Field     | Type        | Null | Key | Default | Extra |
+-----------+-------------+------+-----+---------+-------+
| COLUNA1   | varchar(30) | NO   | PRI | NULL    |       |
| COLUNA2   | varchar(30) | YES  |     | NULL    |       |
| COLUNA3   | varchar(30) | YES  |     | NULL    |       |
| COLUNA    | varchar(30) | YES  |     | NULL    |       |
| COLUNA100 | int(11)     | YES  |     | NULL    |       |
+-----------+-------------+------+-----+---------+-------+
/* ADICIONANDO UMA COLUNA COM POSIÇÃO*/

ALTER TABLE TABELA
ADD COLUMN COLUNA4 VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA3;
+-----------+-------------+------+-----+---------+-------+
| Field     | Type        | Null | Key | Default | Extra |
+-----------+-------------+------+-----+---------+-------+
| COLUNA1   | varchar(30) | NO   | PRI | NULL    |       |
| COLUNA2   | varchar(30) | YES  |     | NULL    |       |
| COLUNA3   | varchar(30) | YES  |     | NULL    |       |
| COLUNA4   | varchar(30) | NO   | UNI | NULL    |       |
| COLUNA    | varchar(30) | YES  |     | NULL    |       |
| COLUNA100 | int(11)     | YES  |     | NULL    |       |
+-----------+-------------+------+-----+---------+-------+

/* MODIFICANDO O TIPO DE UM CAMPO*/

ALTER TABLE TABELA MODIFY COLUNA2 DATE NOT NULL;

/*RENOMEANDO O NOME DA TABELA*/
ALTER TABLE TABELA 
RENAME PESSOA;

CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);

/*FOREIGN KEY*/

ALTER TABLE TIME
ADD FOREIGN KEY (ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

/*VERIFICANDO AS CHAVES*/

SHOW CREATE TABLE TIME;


/*ORGANIZACAO DE CHAVES - CONSTRAINT (REGRA) */
CREATE TABLE JOGADOR (
    IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (30)
);

CREATE TABLE TIMES (
    IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    NOMETIME VARCHAR(30),
    ID_JOGADOR INT,
    FOREIGN KEY(ID_JOGADOR)
    REFERENCES JOGADOR(IDJOGADOR)

);

INSERT INTO JOGADOR VALUES(NULL, 'GUERRERO');
INSERT INTO TIMES VALUES(NULL, 'FLAMENGO',1);

show tables;
DROP TABLE ENDERECO;
DROP TABLE TELEFONE;
DROP TABLE CLIENTE;

CREATE TABLE CLIENTE(
    IDCLIENTE INT,
    NOME VARCHAR(30)
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT,
    TIPO CHAR(3) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (IDCLIENTE);


ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
;

SHOW CREATE TABLE TELEFONE;
/*
| TELEFONE | CREATE TABLE `telefone` (
  `IDTELEFONE` int(11) DEFAULT NULL,
  `TIPO` char(3) NOT NULL,
  `NUMERO` varchar(10) NOT NULL,
  `ID_CLIENTE` int(11) DEFAULT NULL,
  KEY `FK_CLIENTE_TELEFONE` (`ID_CLIENTE`),
  CONSTRAINT `FK_CLIENTE_TELEFONE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`IDCLIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
*/
SHOW DATABASES;
USE information_schema;
DESC TABLE_CONSTRAINTS;

SELECT CONSTRAINT_SCHEMA AS "BANCO",
        TABLE_NAME AS "TABELA",
        CONSTRAINT_TYPE AS "TIPO"
        FROM TABLE_CONSTRAINTS;

        SELECT CONSTRAINT_SCHEMA AS "BANCO",
        TABLE_NAME AS "TABELA",
        CONSTRAINT_TYPE AS "TIPO",
        CONSTRAINT_NAME AS "NOME REGRA" 
        FROM TABLE_CONSTRAINTS
        WHERE CONSTRAINT_SCHEMA = "comercio";

/* APAGANDO CONTRAINTS */
USE COMERCIO;
ALTER TABLE TELEFONE
DROP FOREIGN KEY FK_CLIENTE_TELEFONE;


/* A79 - OFICINA DO SEU ZE */

CREATE DATABASE OFICINA;
CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    SEXO ENUM('M','F')NOT NULL,
    ID_CARRO INT UNIQUE
);
CREATE TABLE TELEFONE (
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES','CEL','COM') NOT NULL,
	NUMERO VARCHAR(30)NOT NULL,
    ID_CLIENTE INT
);
CREATE TABLE MARCA (
    IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);
CREATE TABLE CARRO (
    IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30)NOT NULL,
	PLACA VARCHAR(30)NOT NULL UNIQUE,
    ID_MARCA INT 
);
CREATE TABLE COR (
    IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE CARRO_COR(
    ID_CARRO INT,
    ID_COR INT,
    PRIMARY KEY(ID_CARRO,ID_COR)
);

ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO) 
REFERENCES CARRO(IDCARRO)
;
ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE) 
REFERENCES CLIENTE(IDCLIENTE)
;
ALTER TABLE CARRO 
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA) 
REFERENCES MARCA(IDMARCA)
;
ALTER TABLE CARRO_COR 
ADD CONSTRAINT FK_CARO
FOREIGN KEY(ID_CARRO) 
REFERENCES CARRO(IDCARRO)
;
ALTER TABLE CARRO_COR 
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR) 
REFERENCES COR(IDCOR)
;




/* A 39 ENTENDENDO TRIGGERS */

/* ESTRUTURA DE UMA TRIGGER */

CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW (PARA CADA LINHA)
BEGIN -> INICIO

    QUALQUER COMANDO SQL

END -> FIM

CREATE DATABASE AULA40;
USE AULA40;

CREATE TABLE USUARIO(
    IDUSUARIO INT PRIMARY Key AUTO_INCREMENT,
    NOME VARCHAR(30),
    LOGIN VARCHAR(30),
    SENHA VARCHAR(100)
);

CREATE TABLE BKP_USUARIO(
    IDBACKUP INT PRIMARY Key AUTO_INCREMENT,
    IDUSUARIO INT,
    NOME VARCHAR(30),
    LOGIN VARCHAR(30)
);

/* CRIANDO A TRIGGER */

DELIMITER $

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
    INSERT INTO BKP_USUARIO VALUES (NULL,OLD.IDUSUARIO,OLD.NOME,OLD.LOGIN);
END
$
DELIMITER ;
INSERT INTO USUARIO VALUES(NULL,'ANDRADE','ANDRADE2009','HEXACAMPEAO');
DELETE FROM USUARIO WHERE IDUSUARIO = 2;

CREATE DATABASE LOJA;
CREATE TABLE PRODUTO (
    IDPRODUTO INT PRIMARY Key AUTO_INCREMENT,
    NOME VARCHAR(30),
    VALOR FLOAT(10,2)
);

CREATE DATABASE BACKUP;
USE BACKUP;

CREATE TABLE BKP_PRODUTO (
    IDBKP INT PRIMARY Key AUTO_INCREMENT,
    IDPRODUTO INT,
    NOME VARCHAR(30),
    VALOR FLOAT(10,2)
);

USE LOJA;

INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,1000, 'TESTE',0.0,'I');

SELECT * FROM BACKUP.BKP_PRODUTO;
+-------+-----------+-------+-------+
| IDBKP | IDPRODUTO | NOME  | VALOR |
+-------+-----------+-------+-------+
|     1 |      1000 | TESTE |  0.00 |
+-------+-----------+-------+-------+
/*DROP TRIGGER BACKUP_PRODUT; */
DELIMITER $

CREATE TRIGGER BACKUP_PRODUT
BEFORE INSERT ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,NEW.IDPRODUTO,NEW.NOME,NEW.VALOR);
END
$
DELIMITER ;

INSERT INTO PRODUTO VALUES(NULL, 'TESTE1',1.0);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO MODELAGEM',50.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO BI',80.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO ORACLE',70.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO SQL SERVER',100.00);

DELIMITER $

CREATE TRIGGER BACKUP_PRODUT_DEL
BEFORE DELETE ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,OLD.IDPRODUTO,OLD.NOME,OLD.VALOR);
END
$
DELIMITER ;

DELETE FROM PRODUTO WHERE IDPRODUTO = 2;

DROP TRIGGER BACKUP_PRODUT;


DELIMITER $

CREATE TRIGGER BACKUP_PRODUT
AFTER INSERT ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,NEW.IDPRODUTO,NEW.NOME,NEW.VALOR);
END
$
DELIMITER ;

INSERT INTO PRODUTO VALUES(NULL,'LIVRO C#',100.00);

ALTER TABLE BACKUP.BKP_PRODUTO
ADD EVENTO CHAR (1);

DROP TRIGGER BACKUP_PRODUT_DEL;
/* TRIGER DE DELETE */
DELIMITER $

CREATE TRIGGER BACKUP_PRODUT_DEL
BEFORE DELETE ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,OLD.IDPRODUTO,OLD.NOME,OLD.VALOR,'D');
END
$
DELIMITER ;

DELETE FROM PRODUTO WHERE IDPRODUTO = 4;

mysql> SELECT * FROM PRODUTO;
+-----------+------------------+--------+
| IDPRODUTO | NOME             | VALOR  |
+-----------+------------------+--------+
|         1 | TESTE1           |   1.00 |
|         3 | LIVRO BI         |  80.00 |
|         5 | LIVRO SQL SERVER | 100.00 |
|         6 | LIVRO C#         | 100.00 |
+-----------+------------------+--------+


/* TRIGER DE INSERT */

DELIMITER $

CREATE TRIGGER BACKUP_PRODUT_INSERT
BEFORE INSERT ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,NEW.IDPRODUTO,NEW.NOME,NEW.VALOR,'I');
END
$
DELIMITER ;

INSERT INTO PRODUTO VALUES(NULL,'LIVRO JAVA 2',100.00);


DROP DATABASE LOJA;
DROP DATABASE BACKUP;
CREATE DATABASE LOJA;
USE LOJA;

CREATE TABLE PRODUTO (
    IDPRODUTO INT PRIMARY Key AUTO_INCREMENT,
    NOME VARCHAR(30),
    VALOR FLOAT(10,2)
);

INSERT INTO PRODUTO VALUES(NULL,'LIVRO MODELAGEM',50.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO BI',80.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO ORACLE',70.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO SQL SERVER',100.00);

CREATE DATABASE BACKUP;
USE BACKUP;

/*QUANDO */
SELECT NOW();
/*QUEM */
SELECT CURRENT_USER();

CREATE TABLE BKP_PRODUTO(
    IDPBACKUP INT PRIMARY Key AUTO_INCREMENT,
    IDPRODUTO INT,
    NOME VARCHAR(30),
    VALOR_ORIGINAL FLOAT(10,2),
    VALOR_ALTERADO FLOAT(10,2),
    DATA DATETIME,
    USUARIO VARCHAR(30),
    EVENTO CHAR(1)

);

/* BACKUP DE TRIGGER */

DELIMITER $

CREATE TRIGGER AUDIT_PROD
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,OLD.IDPRODUTO,OLD.NOME,OLD.VALOR,NEW.VALOR,NOW(), CURRENT_USER(),'U');
END
$
DELIMITER ;
SELECT * FROM PRODUTO;

UPDATE PRODUTO SET VALOR = 110.00
WHERE IDPRODUTO=4;

SELECT * FROM PRODUTO;

SELECT * FROM BACKUP.BKP_PRODUTO ;

+-----------+-----------+------------------+----------------+----------------+---------------------+----------------+--------+
| IDPBACKUP | IDPRODUTO | NOME             | VALOR_ORIGINAL | VALOR_ALTERADO | DATA                | USUARIO        | EVENTO |
+-----------+-----------+------------------+----------------+----------------+---------------------+----------------+--------+
|         1 |         4 | LIVRO SQL SERVER |         100.00 |         110.00 | 2024-02-11 07:10:36 | root@localhost | U      |
+-----------+-----------+------------------+----------------+----------------+---------------------+----------------+--------+

/* AUTORELACIONAMENTO */

CREATE TABLE CURSOS (
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    HORAS INT,
    VALOR FLOAT(10,2),
    ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS VALUES (NULL, 'BD RELACIONAL', 20,400.00,NULL);
INSERT INTO CURSOS VALUES (NULL, 'BUSINESS INTELLIGENCE', 40,800.00,1);
INSERT INTO CURSOS VALUES (NULL, 'RELATORIOS AVANCADOS', 20,600.00,2);
INSERT INTO CURSOS VALUES (NULL, 'LOGICA PROGRAM', 20,400.00,NULL);
INSERT INTO CURSOS VALUES (NULL, 'RUBY', 30,500.00,4);

SELECT * FROM CURSOS;
+---------+-----------------------+-------+--------+-----------+
| IDCURSO | NOME                  | HORAS | VALOR  | ID_PREREQ |
+---------+-----------------------+-------+--------+-----------+
|       1 | BD RELACIONAL         |    20 | 400.00 |      NULL |
|       2 | BUSINESS INTELLIGENCE |    40 | 800.00 |         1 |
|       3 | RELATORIOS AVANCADOS  |    20 | 600.00 |         2 |
|       4 | LOGICA PROGRAM        |    20 | 400.00 |      NULL |
|       5 | RUBY                  |    30 | 500.00 |         4 |
+---------+-----------------------+-------+--------+-----------+

SELECT NOME,VALOR,HORAS,IFNULL(ID_PREREQ,"SEM REQ") REQUISITO 
FROM CURSOS;

SELECT C.NOME AS CURSO,
C.VALOR AS VALOR,
C.HORAS AS CARGA,
IFNULL (P.NOME,"---") AS PREREQ
FROM CURSOS C
INNER JOIN CURSOS P
ON P.IDCURSO = C.ID_PREREQ;

+-----------------------+--------+-------+-----------------------+
| CURSO                 | VALOR  | CARGA | PREREQ                |
+-----------------------+--------+-------+-----------------------+
| BUSINESS INTELLIGENCE | 800.00 |    40 | BD RELACIONAL         |
| RELATORIOS AVANCADOS  | 600.00 |    20 | BUSINESS INTELLIGENCE |
| RUBY                  | 500.00 |    30 | LOGICA PROGRAM        |
+-----------------------+--------+-------+-----------------------+

SELECT C.NOME AS CURSO,
C.VALOR AS VALOR,
C.HORAS AS CARGA,
IFNULL (P.NOME,"---") AS PREREQ
FROM CURSOS C LEFT JOIN CURSOS P /* SERVE PARA JUNTAR A ESQUERDA TAMBÉM */

ON P.IDCURSO = C.ID_PREREQ;
+-----------------------+--------+-------+-----------------------+
| CURSO                 | VALOR  | CARGA | PREREQ                |
+-----------------------+--------+-------+-----------------------+
| BD RELACIONAL         | 400.00 |    20 | ---                   |
| BUSINESS INTELLIGENCE | 800.00 |    40 | BD RELACIONAL         |
| RELATORIOS AVANCADOS  | 600.00 |    20 | BUSINESS INTELLIGENCE |
| LOGICA PROGRAM        | 400.00 |    20 | ---                   |
| RUBY                  | 500.00 |    30 | LOGICA PROGRAM        |
+-----------------------+--------+-------+-----------------------+


/* CURSORES */

CREATE DATABASE CURSORES;
USE CURSORES;

CREATE TABLE VENDEDORES (
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (50),
    JAN INT,
    FEV INT,
    MAR INT


);

INSERT INTO VENDEDORES VALUES (NULL,'MAFRA', 32432,232323,53234);
INSERT INTO VENDEDORES VALUES(NULL,'CLARA', 32322,32433,443434);
INSERT INTO VENDEDORES VALUES(NULL,'JOAO', 32322,3242424,545454);
INSERT INTO VENDEDORES VALUES(NULL,'LILIAN', 32444,23444,646545);
INSERT INTO VENDEDORES VALUES(NULL,'ANTONIO', 32452,32455,43436);
INSERT INTO VENDEDORES VALUES(NULL,'GLORIA', 32432,324555,434366);

SELECT * FROM VENDEDORES;
SELECT NOME, (JAN+FEV+MAR) AS TOTAL FROM VENDEDORES;
SELECT NOME, (JAN+FEV+MAR) AS TOTALN, (JAN+FEV+MAR)/3 AS MEDIA FROM VENDEDORES;

CREATE TABLE VEND_TOTAL (
    NOME VARCHAR (50),
    JAN INT,
    FEV INT,
    MAR INT,
    TOTAL INT,
    MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN 
        DECLARE FIM INT DEFAULT 0;
        DECLARE VAR1,VAR2,VAR3, VTOTAL,VMEDIA INT;
        DECLARE VNOME VARCHAR(50);

        DECLARE REG CURSOR FOR (
            SELECT NOME,JAN,FEV,MAR FROM VENDEDORES
        );

        DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM =1;

        OPEN REG;

        REPEAT

        FETCH REG INTO VNOME, VAR1,VAR2,VAR3;
        IF NOT FIM THEN

            SET VTOTAL = VAR1 +VAR2 + VAR3;
            SET VMEDIA = VTOTAL /3;

            INSERT INTO VEND_TOTAL VALUES(VNOME,VAR1,VAR2,VAR3,VTOTAL,VMEDIA);

        END IF;

        UNTIL FIM END REPEAT;

        CLOSE REG;

END
$

SELECT * FROM VENDEDORES;
SELECT * FROM VEND_TOTAL;

mysql> SELECT * FROM VENDEDORES;
+------------+---------+-------+---------+--------+
| IDVENDEDOR | NOME    | JAN   | FEV     | MAR    |
+------------+---------+-------+---------+--------+
|          1 | MAFRA   | 32432 |  232323 |  53234 |
|          2 | CLARA   | 32322 |   32433 | 443434 |
|          3 | JOAO    | 32322 | 3242424 | 545454 |
|          4 | LILIAN  | 32444 |   23444 | 646545 |
|          5 | ANTONIO | 32452 |   32455 |  43436 |
|          6 | GLORIA  | 32432 |  324555 | 434366 |
+------------+---------+-------+---------+--------+
6 rows in set (0.00 sec)

mysql> SELECT * FROM VEND_TOTAL;
Empty set (0.01 sec)

CALL INSEREDADOS();

mysql> SELECT * FROM VEND_TOTAL
    -> ;
+---------+-------+---------+--------+---------+---------+
| NOME    | JAN   | FEV     | MAR    | TOTAL   | MEDIA   |
+---------+-------+---------+--------+---------+---------+
| MAFRA   | 32432 |  232323 |  53234 |  317989 |  105996 |
| CLARA   | 32322 |   32433 | 443434 |  508189 |  169396 |
| JOAO    | 32322 | 3242424 | 545454 | 3820200 | 1273400 |
| LILIAN  | 32444 |   23444 | 646545 |  702433 |  234144 |
| ANTONIO | 32452 |   32455 |  43436 |  108343 |   36114 |
| GLORIA  | 32432 |  324555 | 434366 |  791353 |  263784 |
+---------+-------+---------+--------+---------+---------+

CREATE DATABASE CONSULTORIO;
USE CONSULTORIO;

CREATE TABLE PACIENTE (
    IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    NASCIMENTO DATE

);
CREATE TABLE MEDICO (
    IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    SEXO CHAR(1),
    ESPECIALIDADE VARCHAR(30),
    FUNCIONARIO ENUM ('S','N')   

);

CREATE TABLE HOSPITAL (
    IDHOSPITAL INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    SEXO CHAR(1),
    BAIRRO VARCHAR(30),
    CIDADE VARCHAR(30),    
    ESTADO CHAR(2)
);

CREATE TABLE CONSULTA (
    IDCONSULTA INT PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE INT,
    ID_MEDICO INT,
    ID_HOSPITAL INT,
    DATA DATETIME,
    DIAGNOSTICO VARCHAR(50)

);

CREATE TABLE INTERNACAO (
    IDINTERNACAO INT PRIMARY KEY AUTO_INCREMENT,
    ENTRADA DATETIME,
    QUARTO INT,
    SAIDA DATETIME,
    OBSERVACOES VARCHAR(50),
    ID_CONSULTA INT UNIQUE



);

/* CRIANDO AS CONSTRAINTS - CORRECAO */

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_PACIENTE
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_MEDICO
FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(IDMEDICO);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_HOSPITAL
FOREIGN KEY(ID_HOSPITAL) REFERENCES HOSPITAL(IDHOSPITAL);

ALTER TABLE INTERNACAO ADD CONSTRAINT FK_INTERACAO_CONSULTA
FOREIGN KEY(ID_CONSULTA) REFERENCES CONSULTA(IDCONSULTA);












